# FedOPF: HFL approach based on APPFL


In [1]:
import argparse
from omegaconf import OmegaConf
from appfl.agent import ClientAgent, ServerAgent

import time

[W112 10:20:06.833117467 Context.cpp:281] Warning: torch.backends.cuda.preferred_linalg_library is an experimental feature. If you see any error or unexpected behavior when this flag is set please file an issue on GitHub. (function operator())


In [2]:
cu_config_path = "./resources/configs/fedopf_central_unit_hfl.yaml"
server_config_path = "./resources/configs/fedopf_server_hfl.yaml"
client_config_path = "./resources/configs/fedopf_client_1.yaml"

client_ids = [14, 57, 60, 73, 89, 118, 162, 197, 250, 793, 1354, 1664]
# client_ids = [14, 250, 118, 89, 1354, 1664, 197, 60, 73, 57, 162, 793]
num_clients = len(client_ids)

In [3]:
central_unit_config = OmegaConf.load(cu_config_path) # Load central unit configs for HFL

# Load server agent config and set corresponding fields for # of clusters (CFL_GP)
n_models = central_unit_config.cu_configs.n_models
server_agent_configs = [
    OmegaConf.load(server_config_path) for _ in range(n_models)
]
# server_agent_config.server_configs.num_clients = num_clients
# Create server agent (CFL_GP)
server_agents = [ServerAgent(server_agent_config=server_agent_configs[i]) for i in range(n_models)]

# Create global agent (for foundation model <== HFL)
global_agent_config = OmegaConf.load(server_config_path)
global_agent = ServerAgent(server_agent_config=global_agent_config)

appfl: ✅[2026-01-12 05:12:15,643 server]: Logging to ./output/result_Server_2026-01-12-05-12-15.txt


In [4]:
# Load base client configurations and set corresponding fields for different clients
client_agent_configs = [
    OmegaConf.load(client_config_path) for _ in range(num_clients)
]

for i, id in enumerate(client_ids):
    client_agent_configs[i].client_id = f"Client{i+1}"
    # client_agent_configs[i].data_configs.dataset_kwargs.num_clients = num_clients
    client_agent_configs[i].data_configs.dataset_kwargs.client_id = id
    # client_agent_configs[i].data_configs.dataset_kwargs.visualization = (
    #     True if i == 0 else False
    # )
    
    # only enable wandb for the first client is sufficient for logging all clients in serial run
    if hasattr(client_agent_configs[i], "wandb_configs") and client_agent_configs[i].wandb_configs.get("enable_wandb", False):
        if i == 0:
            client_agent_configs[i].wandb_configs.enable_wandb = True
        else:
            client_agent_configs[i].wandb_configs.enable_wandb = False

In [5]:
# Load client agents
client_agents = [
    ClientAgent(client_agent_config=client_agent_configs[i]) for i in range(num_clients)
]

appfl: ✅[2026-01-12 05:12:15,896 Client1]: Logging to ./output/result_Client1_2026-01-12-05-12-15.txt
/home/super/data1/skj/FedOPF-APPFL/HFL/resources/dataset/acopf_prob_advanced.py:134: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:253.)
  self.slackva = torch.tensor([np.deg2rad(ppc['bus'][self.slack, idx_bus.VA])],
appfl: ✅[2026-01-12 05:12:17,020 Client2]: Logging to ./output/result_Client2_2026-01-12-05-12-17.txt
INFO:appfl.logger.client_logger_Client2:Logging to ./output/result_Client2_2026-01-12-05-12-17.txt
appfl: ✅[2026-01-12 05:12:17,441 Client3]: Logging to ./output/result_Client3_2026-01-12-05-12-17.txt
INFO:appfl.logger.client_logger_Client3:Logging to ./output/result_Client3_2026-01-12-05-12-17.txt
appfl: ✅[2026-01-12 05:12:17,823 Client4]: Logging to ./output/resu

In [6]:
# Get additional client configurations from the server
client_config_from_server = server_agents[0].get_client_configs()
# print(OmegaConf.to_yaml(server_agent.get_client_configs()))
client_config_from_server.model_configs.model_name = 'GraphOPF'
client_config_from_server.model_configs.model_path = "./resources/model/graphopf_client.py"

for client_agent in client_agents:
    client_config_from_server.model_configs.model_kwargs.client_id = client_agent.dataset.nbus
    client_agent.load_config(client_config_from_server)

In [7]:
central_unit_config.cu_configs

{'gg_correction_period': 1, 'n_models': 4, 'clustering_period': 2, 'clustering_termination_threshold': 50, 'cu_compressor_configs': {'use_reduced_G': False, 'gradient_compression_ratio': 100}, 'num_comm_rounds': 200, 'unknown_k': False, 'warmup_epoch': 0, 'checkpoints_interval': 100}

In [8]:
import torch
import numpy as np 
from utils.cfl_gp import get_num_cluster, spectral_clustering_and_matching
from collections import OrderedDict # NOTE: kj
import copy

def get_mdl_params(model_params):
    n_par=0
    for name, param in model_params:
        n_par += len(param.data.reshape(-1))
    param_mat = np.zeros(n_par).astype('float32')
    idx = 0
    for name, param in model_params:
        temp = param.data.cpu().numpy().reshape(-1)
        param_mat[idx:idx + len(temp)] = temp
        idx += len(temp)
    return np.copy(param_mat)

# Main code: run HFL
# HFL parameters
clustering_period = central_unit_config.cu_configs.clustering_period
gg_correction_period = central_unit_config.cu_configs.gg_correction_period
use_reduced_G = central_unit_config.cu_configs.cu_compressor_configs.use_reduced_G
gradient_compression_ratio = central_unit_config.cu_configs.cu_compressor_configs.gradient_compression_ratio
clustering_termination_threshold = central_unit_config.cu_configs.clustering_termination_threshold
estimated_cluster_ids = None
estimated_cluster_ids_new = None
unknown_k = central_unit_config.cu_configs.unknown_k
warmup_epoch = central_unit_config.cu_configs.warmup_epoch
save_checkpoint_interval = central_unit_config.cu_configs.checkpoints_interval

n_params_per_model = sum(param.numel() for param in server_agents[0].model.parameters())
n_params_compressed_gradient = n_params_per_model
if use_reduced_G:
    n_params_compressed_gradient = n_params_per_model // gradient_compression_ratio
    random_G_indices = np.random.choice(np.arange(n_params_per_model), size=n_params_compressed_gradient, replace=False)
print("n_params_per_model: ", n_params_per_model)
print("n_params_compressed_gradient: ", n_params_compressed_gradient)

gradient_profile_matrix = np.zeros(shape=(n_models * n_params_compressed_gradient, num_clients))
criterion_model_index = 0
CLUSTERING_CONVERGENCE = False

# group-global corr. update
group_global_state_param_list = np.zeros((n_models, n_params_compressed_gradient)) # .astype('float32')        

metrics = {} # data tracking

for round in range(central_unit_config.cu_configs.num_comm_rounds):
    # Model save
    if round == central_unit_config.cu_configs.num_comm_rounds-1:
        for client_agent in client_agents:
            client_agent.save_checkpoint()
        for m in range(n_models):
            server_agents[m].save_checkpoint(server_id=m)
        global_agent.save_checkpoint(server_id=-1)

    if round != 0:
        # Load the new global model from the server
        for cluster_idx, client_cluster in enumerate(client_clusters):
            print("load new group model")
            for client, new_global_model_future in zip(client_cluster, group_global_models[cluster_idx]):
                client.load_parameters(new_global_model_future.result())

    cr_start_time = time.time()
    for c_idx, client_agent in enumerate(client_agents):
        # - Select models for downlink transmission
        if round % clustering_period == 0 and CLUSTERING_CONVERGENCE is not True:
            if round == 0:
                query_model_indicies = [0]
            elif estimated_cluster_ids[c_idx] == criterion_model_index:
                query_model_indicies = [estimated_cluster_ids[c_idx]]
            else:
                query_model_indicies = [criterion_model_index, estimated_cluster_ids[c_idx]]
        else:
            query_model_indicies = [estimated_cluster_ids[c_idx]]
        
        # - local update or gradient calculation
        for model_idx in query_model_indicies:
            if round == 0:
                estimated_cluster_id = 0
                # Load initial global model from the server
                init_global_model = server_agents[estimated_cluster_id].get_parameters(serial_run=True)
                client_agent.load_parameters(init_global_model)
            else:
                estimated_cluster_id = estimated_cluster_ids[c_idx]  
                print(server_agents[estimated_cluster_id].get_parameters(serial_run=True)['layers.0.edge_aggr.0.weight'][:2,:])
            
            group_global_state_param_list_ = torch.tensor(group_global_state_param_list[estimated_cluster_id], dtype=torch.float32)        
            ## client local training
            client_agent.train(round=round, gg_corr_params=group_global_state_param_list_)
            local_model = client_agent.get_parameters()
            if isinstance(local_model, tuple):
                local_model, metadata = local_model[0], local_model[1]
            else:
                metadata = {}

            ## NOTE: kj
            local_model = OrderedDict((k,v) for k,v in local_model.items() if k.startswith("layers"))
            if round % clustering_period == 0 and model_idx == criterion_model_index and CLUSTERING_CONVERGENCE is not True:
                # vectorized_model_info = flatten_tensor(local_model).clone().cpu().detach().numpy() ~~~ # <== shared NNs 이 들어가야 함! "local_model" 자체가 애초에 shared layers를 불러오게끔 세팅되어 있음.
                vectorized_model_info = torch.cat([value.flatten() for value in local_model.values()])
                vectorized_model_info = vectorized_model_info.clone().cpu().detach().numpy()
                if use_reduced_G is True:
                    selected_vectorized_model_info = vectorized_model_info[random_G_indices]
                    vectorized_model_info = selected_vectorized_model_info

                # Cumulative Averaging
                beta = (1 / (np.floor((round + 1) / (n_models * clustering_period)) + 1))
                # global_logger.info("beta:{}".format(beta))
                gradient_profile_matrix[(criterion_model_index)*n_params_compressed_gradient : (criterion_model_index + 1)*n_params_compressed_gradient,c_idx] = \
                    gradient_profile_matrix[(criterion_model_index)*n_params_compressed_gradient : (criterion_model_index + 1)*n_params_compressed_gradient,c_idx] * \
                        (1 - beta) + (beta) * vectorized_model_info

    # - Clustering & Matching
    if unknown_k is True and round < warmup_epoch:
        proposed_k = get_num_cluster(gradient_profile_matrix, n_centers=n_models,
                                        n_clients=num_clients,
                                        estimated_cluster_ids_old=estimated_cluster_ids)
        estimated_cluster_ids = np.zeros(shape=num_clients, dtype=int)
        estimated_cluster_ids_new = np.zeros(shape=num_clients, dtype=int)
        consistency_cnt = 0
    elif unknown_k is True and round == warmup_epoch:
        n_models = get_num_cluster(gradient_profile_matrix, n_centers=n_models,
                                        n_clients=num_clients,
                                        estimated_cluster_ids_old=estimated_cluster_ids)
        group_global_models = [[] for _ in range(n_models)]
        print("Set number of clusters as {}.".format(n_models))

        for m in np.arange(1, n_models):
            # copy_weight2(target=self.models[m], source=self.models[0])
            server_agents[m].model.load_state_dict(server_agents[0].get_parameters(serial_run=True))
    
        estimated_cluster_ids = np.zeros(shape=num_clients, dtype=int)
        estimated_cluster_ids_new = np.zeros(shape=num_clients, dtype=int)
        consistency_cnt = 0
    elif round % clustering_period == 0 and round < clustering_termination_threshold:
        print("sepctral_clustering_and_matching")
        # print(gradient_profile_matrix.shape)
        criterion_model_index = (criterion_model_index + 1) % n_models
        info = spectral_clustering_and_matching(gradient_profile_matrix, n_centers=n_models,
                                                n_clients=num_clients,
                                                estimated_cluster_ids_old=estimated_cluster_ids,
                                                clustering_algorithm='KMeans') # KMeans, DBSCAN, AgglomerativeClustering
        estimated_cluster_ids_new = info["estimated_cluster_ids"]  # update cluster ids.
        reduced_gradient_profile_matrix = info["reduced_gradient_profile_matrix"]
        singular_values = info["singular_values"]

        estimated_cluster_ids = estimated_cluster_ids_new  # np.zeros(shape=self.n_clients, dtype=int)        

    print("cluster ids: {}".format(estimated_cluster_ids))

    # - Model update
    group_global_models = [[] for _ in range(n_models)]
    clustered_client_indices = [np.where(estimated_cluster_ids == cluster_id)[0] for cluster_id in range(n_models)]
    client_clusters = [[client_agents[i] for i in client_indices] for client_indices in clustered_client_indices]
    for cluster_idx, client_cluster in enumerate(client_clusters):
        if len(client_cluster) >= 1:
            # print("group model update!")
            server_agents[cluster_idx].num_clients = len(client_cluster)
            # server_agents[cluster_idx]._set_num_clients()

            # TODO: Check handling server configs for clustered FL. 
            server_agents[cluster_idx].aggregator.aggregator_configs.num_clients = len(client_cluster)
            server_agents[cluster_idx].scheduler.num_clients = len(client_cluster)
            # server_agents[cluster_idx]._load_scheduler()
            # server_agents[cluster_idx].scheduler.aggregation_kwargs['num_clients'] = len(client_cluster)

            for client in client_cluster:
                c_model = client.get_parameters()
                if isinstance(c_model, tuple):
                    c_model, metadata = c_model[0], c_model[1]
                else:
                    metadata = {}
                ## NOTE: kj
                c_model = OrderedDict((k,v) for k,v in c_model.items() if k.startswith("layers"))
                # "Send" local model to server and get a Future object for the new global model
                # The Future object will be resolved when the server receives local models from all clients
                new_global_model_future = server_agents[cluster_idx].global_update(
                    client_id=client.get_id(),
                    local_model=c_model,
                    blocking=False, # False
                    **metadata,
                )
                group_global_models[cluster_idx].append(new_global_model_future)

    # Group-Global Correction
    if round % gg_correction_period == 0:
        print("Update Group model and GG-Correction.")
        global_models = []
        for client_agent in client_agents:
            local_model_gg = client_agent.get_parameters()
            if isinstance(local_model_gg, tuple):
                local_model_gg, metadata = local_model_gg[0], local_model_gg[1]
            else:
                metadata = {}
            ## NOTE: kj
            local_model_gg = OrderedDict((k,v) for k,v in local_model_gg.items() if k.startswith("layers"))
            # "Send" local model to server and get a Future object for the new global model
            # The Future object will be resolved when the server receives local models from all clients
            new_global_model = global_agent.global_update(
                client_id=client_agent.get_id(),
                local_model=local_model_gg,
                blocking=False,
                **metadata,
            )
            global_models.append(new_global_model)

        beta_ = 0.9
        for m in range(n_models):
            # group_models_params = get_mdl_params(server_agents[m].get_parameters(init_model=False).items())
            # global_model_params = get_mdl_params(global_agent.get_parameters(init_model=False).items())
            group_models_params = get_mdl_params(server_agents[m].get_parameters(serial_run=True).items())
            global_model_params = get_mdl_params(global_agent.get_parameters(serial_run=True).items())
            group_global_state_param_list[m,:] = (1-beta_)*group_global_state_param_list[m,:] + beta_*(group_models_params - global_model_params)

    time_for_communication_round = time.time() - cr_start_time
    # ====================================
    # Data Tracking and save Results
    # ====================================
    data_tracking = {
        "estimated_cluster_ids": copy.deepcopy(estimated_cluster_ids),
        "reduced_gradient_profile_matrix": copy.deepcopy(reduced_gradient_profile_matrix),
        # "singular_values": copy.deepcopy(self.singular_values),
        "time_for_communication_round": time_for_communication_round
    }
    metrics["c_round_" + str(round)] = data_tracking
    if round == central_unit_config.cu_configs.num_comm_rounds-1: 
        global_agent.save_data_tracking(metrics)

n_params_per_model:  973050
n_params_compressed_gradient:  973050


appfl: ✅[2026-01-12 05:12:39,178 Client1]:      Round      Epoch       Time Train Loss Train Accuracy
INFO:appfl.logger.client_logger_Client1:     Round      Epoch       Time Train Loss Train Accuracy
appfl: ✅[2026-01-12 05:12:40,524 Client1]:          0          0     1.3298     0.8421           72.4
INFO:appfl.logger.client_logger_Client1:         0          0     1.3298     0.8421           72.4
appfl: ✅[2026-01-12 05:12:41,196 Client1]:          0          1     0.6699     0.2932           91.2
INFO:appfl.logger.client_logger_Client1:         0          1     0.6699     0.2932           91.2
appfl: ✅[2026-01-12 05:12:41,810 Client1]:          0          2     0.6116     0.2484           74.4
INFO:appfl.logger.client_logger_Client1:         0          2     0.6116     0.2484           74.4
appfl: ✅[2026-01-12 05:12:42,438 Client1]:          0          3     0.6249     0.2620           81.2
INFO:appfl.logger.client_logger_Client1:         0          3     0.6249     0.2620           

sepctral_clustering_and_matching
cluster ids: [0 0 2 0 0 0 0 3 0 1 1 0]
Update Group model and GG-Correction.
load new group model
load new group model
load new group model
load new group model
tensor([[ 0.2684,  0.2911, -0.0850,  0.3216, -0.0761,  0.0742, -0.1706,  0.2045],
        [ 0.3077, -0.2608,  0.3003,  0.0591,  0.2564,  0.0450,  0.1695, -0.0450]])


appfl: ✅[2026-01-12 05:14:39,428 Client1]:          1          0     0.5728     0.3961           77.2
INFO:appfl.logger.client_logger_Client1:         1          0     0.5728     0.3961           77.2
appfl: ✅[2026-01-12 05:14:39,995 Client1]:          1          1     0.5652     0.2506           92.8
INFO:appfl.logger.client_logger_Client1:         1          1     0.5652     0.2506           92.8
appfl: ✅[2026-01-12 05:14:40,572 Client1]:          1          2     0.5740     0.2371           94.0
INFO:appfl.logger.client_logger_Client1:         1          2     0.5740     0.2371           94.0
appfl: ✅[2026-01-12 05:14:41,139 Client1]:          1          3     0.5646     0.2331           93.6
INFO:appfl.logger.client_logger_Client1:         1          3     0.5646     0.2331           93.6
appfl: ✅[2026-01-12 05:14:41,709 Client1]:          1          4     0.5682     0.2308           96.8
INFO:appfl.logger.client_logger_Client1:         1          4     0.5682     0.2308           

tensor([[ 0.2684,  0.2911, -0.0850,  0.3216, -0.0761,  0.0742, -0.1706,  0.2045],
        [ 0.3077, -0.2608,  0.3003,  0.0591,  0.2564,  0.0450,  0.1695, -0.0450]])


appfl: ✅[2026-01-12 05:14:43,854 Client2]:          1          0     0.6278     3.9922       93.42857
INFO:appfl.logger.client_logger_Client2:         1          0     0.6278     3.9922       93.42857
appfl: ✅[2026-01-12 05:14:44,488 Client2]:          1          1     0.6324     3.9451       94.85714
INFO:appfl.logger.client_logger_Client2:         1          1     0.6324     3.9451       94.85714
appfl: ✅[2026-01-12 05:14:45,115 Client2]:          1          2     0.6239     3.9318       95.71429
INFO:appfl.logger.client_logger_Client2:         1          2     0.6239     3.9318       95.71429
appfl: ✅[2026-01-12 05:14:45,783 Client2]:          1          3     0.6654     3.9236      94.571434
INFO:appfl.logger.client_logger_Client2:         1          3     0.6654     3.9236      94.571434
appfl: ✅[2026-01-12 05:14:46,484 Client2]:          1          4     0.6971     3.9254       94.28572
INFO:appfl.logger.client_logger_Client2:         1          4     0.6971     3.9254       94.2

tensor([[ 0.2825,  0.2864, -0.0914,  0.3210, -0.0666,  0.0822, -0.1639,  0.1911],
        [ 0.3291, -0.2610,  0.3038,  0.0598,  0.2395,  0.0266,  0.1511, -0.0325]])


appfl: ✅[2026-01-12 05:14:48,900 Client3]:          1          0     0.7068    16.3786          100.0
INFO:appfl.logger.client_logger_Client3:         1          0     0.7068    16.3786          100.0
appfl: ✅[2026-01-12 05:14:49,587 Client3]:          1          1     0.6846    13.6989          100.0
INFO:appfl.logger.client_logger_Client3:         1          1     0.6846    13.6989          100.0
appfl: ✅[2026-01-12 05:14:50,275 Client3]:          1          2     0.6854    13.6716          100.0
INFO:appfl.logger.client_logger_Client3:         1          2     0.6854    13.6716          100.0
appfl: ✅[2026-01-12 05:14:50,968 Client3]:          1          3     0.6888    10.7747          100.0
INFO:appfl.logger.client_logger_Client3:         1          3     0.6888    10.7747          100.0
appfl: ✅[2026-01-12 05:14:51,674 Client3]:          1          4     0.7033    13.2903          100.0
INFO:appfl.logger.client_logger_Client3:         1          4     0.7033    13.2903          1

tensor([[ 0.2684,  0.2911, -0.0850,  0.3216, -0.0761,  0.0742, -0.1706,  0.2045],
        [ 0.3077, -0.2608,  0.3003,  0.0591,  0.2564,  0.0450,  0.1695, -0.0450]])


appfl: ✅[2026-01-12 05:14:54,332 Client4]:          1          0     0.9439    75.3653       99.45455
INFO:appfl.logger.client_logger_Client4:         1          0     0.9439    75.3653       99.45455
appfl: ✅[2026-01-12 05:14:55,055 Client4]:          1          1     0.7210    74.1576       99.45455
INFO:appfl.logger.client_logger_Client4:         1          1     0.7210    74.1576       99.45455
appfl: ✅[2026-01-12 05:14:55,730 Client4]:          1          2     0.6721    74.0773       99.87879
INFO:appfl.logger.client_logger_Client4:         1          2     0.6721    74.0773       99.87879
appfl: ✅[2026-01-12 05:14:56,370 Client4]:          1          3     0.6373    74.0681       99.45455
INFO:appfl.logger.client_logger_Client4:         1          3     0.6373    74.0681       99.45455
appfl: ✅[2026-01-12 05:14:57,065 Client4]:          1          4     0.6926    74.1011      99.818184
INFO:appfl.logger.client_logger_Client4:         1          4     0.6926    74.1011      99.81

tensor([[ 0.2684,  0.2911, -0.0850,  0.3216, -0.0761,  0.0742, -0.1706,  0.2045],
        [ 0.3077, -0.2608,  0.3003,  0.0591,  0.2564,  0.0450,  0.1695, -0.0450]])


appfl: ✅[2026-01-12 05:14:59,506 Client5]:          1          0     0.7547    12.0687       82.83334
INFO:appfl.logger.client_logger_Client5:         1          0     0.7547    12.0687       82.83334
appfl: ✅[2026-01-12 05:15:00,205 Client5]:          1          1     0.6974    11.0878       87.66667
INFO:appfl.logger.client_logger_Client5:         1          1     0.6974    11.0878       87.66667
appfl: ✅[2026-01-12 05:15:00,933 Client5]:          1          2     0.7256    11.0394       85.83334
INFO:appfl.logger.client_logger_Client5:         1          2     0.7256    11.0394       85.83334
appfl: ✅[2026-01-12 05:15:01,650 Client5]:          1          3     0.7132    10.7058       83.16667
INFO:appfl.logger.client_logger_Client5:         1          3     0.7132    10.7058       83.16667
appfl: ✅[2026-01-12 05:15:02,365 Client5]:          1          4     0.7122    10.8951       85.50001
INFO:appfl.logger.client_logger_Client5:         1          4     0.7122    10.8951       85.5

tensor([[ 0.2684,  0.2911, -0.0850,  0.3216, -0.0761,  0.0742, -0.1706,  0.2045],
        [ 0.3077, -0.2608,  0.3003,  0.0591,  0.2564,  0.0450,  0.1695, -0.0450]])


appfl: ✅[2026-01-12 05:15:04,870 Client6]:          1          0     0.7306    11.1725       91.03704
INFO:appfl.logger.client_logger_Client6:         1          0     0.7306    11.1725       91.03704
appfl: ✅[2026-01-12 05:15:05,577 Client6]:          1          1     0.7042    10.0319       98.92593
INFO:appfl.logger.client_logger_Client6:         1          1     0.7042    10.0319       98.92593
appfl: ✅[2026-01-12 05:15:06,291 Client6]:          1          2     0.7113     9.8893      98.740746
INFO:appfl.logger.client_logger_Client6:         1          2     0.7113     9.8893      98.740746
appfl: ✅[2026-01-12 05:15:06,993 Client6]:          1          3     0.6988     9.8767      98.888885
INFO:appfl.logger.client_logger_Client6:         1          3     0.6988     9.8767      98.888885
appfl: ✅[2026-01-12 05:15:07,736 Client6]:          1          4     0.7408     9.8525       98.51851
INFO:appfl.logger.client_logger_Client6:         1          4     0.7408     9.8525       98.5

tensor([[ 0.2684,  0.2911, -0.0850,  0.3216, -0.0761,  0.0742, -0.1706,  0.2045],
        [ 0.3077, -0.2608,  0.3003,  0.0591,  0.2564,  0.0450,  0.1695, -0.0450]])


appfl: ✅[2026-01-12 05:15:10,296 Client7]:          1          0     0.8186    27.2485           98.5
INFO:appfl.logger.client_logger_Client7:         1          0     0.8186    27.2485           98.5
appfl: ✅[2026-01-12 05:15:11,070 Client7]:          1          1     0.7724    12.0124          100.0
INFO:appfl.logger.client_logger_Client7:         1          1     0.7724    12.0124          100.0
appfl: ✅[2026-01-12 05:15:11,864 Client7]:          1          2     0.7916    11.9534          100.0
INFO:appfl.logger.client_logger_Client7:         1          2     0.7916    11.9534          100.0
appfl: ✅[2026-01-12 05:15:12,719 Client7]:          1          3     0.8527    12.0431       99.83334
INFO:appfl.logger.client_logger_Client7:         1          3     0.8527    12.0431       99.83334
appfl: ✅[2026-01-12 05:15:13,678 Client7]:          1          4     0.9551    11.8897          100.0
INFO:appfl.logger.client_logger_Client7:         1          4     0.9551    11.8897          1

tensor([[ 0.2672,  0.2875, -0.0991,  0.3244, -0.0658,  0.0836, -0.1946,  0.1959],
        [ 0.3210, -0.2523,  0.3140,  0.0576,  0.2613,  0.0514,  0.1600, -0.0589]])


appfl: ✅[2026-01-12 05:15:16,540 Client8]:          1          0     0.8524     0.3150          100.0
INFO:appfl.logger.client_logger_Client8:         1          0     0.8524     0.3150          100.0
appfl: ✅[2026-01-12 05:15:17,280 Client8]:          1          1     0.7378     0.1266          100.0
INFO:appfl.logger.client_logger_Client8:         1          1     0.7378     0.1266          100.0
appfl: ✅[2026-01-12 05:15:18,021 Client8]:          1          2     0.7391     0.0691       99.65715
INFO:appfl.logger.client_logger_Client8:         1          2     0.7391     0.0691       99.65715
appfl: ✅[2026-01-12 05:15:18,797 Client8]:          1          3     0.7745     0.0747          100.0
INFO:appfl.logger.client_logger_Client8:         1          3     0.7745     0.0747          100.0
appfl: ✅[2026-01-12 05:15:19,530 Client8]:          1          4     0.7317     0.0472      99.828575
INFO:appfl.logger.client_logger_Client8:         1          4     0.7317     0.0472      99.82

tensor([[ 0.2684,  0.2911, -0.0850,  0.3216, -0.0761,  0.0742, -0.1706,  0.2045],
        [ 0.3077, -0.2608,  0.3003,  0.0591,  0.2564,  0.0450,  0.1695, -0.0450]])


appfl: ✅[2026-01-12 05:15:22,712 Client9]:          1          0     0.9266     0.9733          100.0
INFO:appfl.logger.client_logger_Client9:         1          0     0.9266     0.9733          100.0
appfl: ✅[2026-01-12 05:15:23,610 Client9]:          1          1     0.8964     0.1266          100.0
INFO:appfl.logger.client_logger_Client9:         1          1     0.8964     0.1266          100.0
appfl: ✅[2026-01-12 05:15:24,551 Client9]:          1          2     0.9386     0.1256          100.0
INFO:appfl.logger.client_logger_Client9:         1          2     0.9386     0.1256          100.0
appfl: ✅[2026-01-12 05:15:25,439 Client9]:          1          3     0.8858     0.1214          100.0
INFO:appfl.logger.client_logger_Client9:         1          3     0.8858     0.1214          100.0
appfl: ✅[2026-01-12 05:15:26,289 Client9]:          1          4     0.8483     0.1268          100.0
INFO:appfl.logger.client_logger_Client9:         1          4     0.8483     0.1268          1

tensor([[ 0.2671,  0.2908, -0.0889,  0.3199, -0.0759,  0.0729, -0.1763,  0.2051],
        [ 0.3089, -0.2578,  0.3050,  0.0629,  0.2631,  0.0497,  0.1648, -0.0548]])


appfl: ✅[2026-01-12 05:15:29,755 Client10]:          1          0     1.6468    55.1494       95.46067
INFO:appfl.logger.client_logger_Client10:         1          0     1.6468    55.1494       95.46067
appfl: ✅[2026-01-12 05:15:31,160 Client10]:          1          1     1.4029    35.4337        96.1573
INFO:appfl.logger.client_logger_Client10:         1          1     1.4029    35.4337        96.1573
appfl: ✅[2026-01-12 05:15:32,586 Client10]:          1          2     1.4251    33.2004       97.34832
INFO:appfl.logger.client_logger_Client10:         1          2     1.4251    33.2004       97.34832
appfl: ✅[2026-01-12 05:15:34,005 Client10]:          1          3     1.4171    33.1865       95.91011
INFO:appfl.logger.client_logger_Client10:         1          3     1.4171    33.1865       95.91011
appfl: ✅[2026-01-12 05:15:35,413 Client10]:          1          4     1.4066    32.3814       97.66293
INFO:appfl.logger.client_logger_Client10:         1          4     1.4066    32.3814 

tensor([[ 0.2671,  0.2908, -0.0889,  0.3199, -0.0759,  0.0729, -0.1763,  0.2051],
        [ 0.3089, -0.2578,  0.3050,  0.0629,  0.2631,  0.0497,  0.1648, -0.0548]])


appfl: ✅[2026-01-12 05:15:41,683 Client11]:          1          0     3.5490   243.5887      83.223076
INFO:appfl.logger.client_logger_Client11:         1          0     3.5490   243.5887      83.223076
appfl: ✅[2026-01-12 05:15:44,296 Client11]:          1          1     2.6106   171.2407           88.5
INFO:appfl.logger.client_logger_Client11:         1          1     2.6106   171.2407           88.5
appfl: ✅[2026-01-12 05:15:46,927 Client11]:          1          2     2.6295   163.1098       89.49232
INFO:appfl.logger.client_logger_Client11:         1          2     2.6295   163.1098       89.49232
appfl: ✅[2026-01-12 05:15:49,545 Client11]:          1          3     2.6153   155.1607      90.230774
INFO:appfl.logger.client_logger_Client11:         1          3     2.6153   155.1607      90.230774
appfl: ✅[2026-01-12 05:15:52,207 Client11]:          1          4     2.6607   150.5705      90.076935
INFO:appfl.logger.client_logger_Client11:         1          4     2.6607   150.5705 

tensor([[ 0.2684,  0.2911, -0.0850,  0.3216, -0.0761,  0.0742, -0.1706,  0.2045],
        [ 0.3077, -0.2608,  0.3003,  0.0591,  0.2564,  0.0450,  0.1695, -0.0450]])


appfl: ✅[2026-01-12 05:15:58,894 Client12]:          1          0     4.5389    23.4385      93.769226
INFO:appfl.logger.client_logger_Client12:         1          0     4.5389    23.4385      93.769226
appfl: ✅[2026-01-12 05:16:02,410 Client12]:          1          1     3.5138     0.2957      98.641014
INFO:appfl.logger.client_logger_Client12:         1          1     3.5138     0.2957      98.641014
appfl: ✅[2026-01-12 05:16:06,072 Client12]:          1          2     3.6604     0.2096           98.0
INFO:appfl.logger.client_logger_Client12:         1          2     3.6604     0.2096           98.0
appfl: ✅[2026-01-12 05:16:09,739 Client12]:          1          3     3.6665     0.2007      99.794876
INFO:appfl.logger.client_logger_Client12:         1          3     3.6665     0.2007      99.794876
appfl: ✅[2026-01-12 05:16:13,328 Client12]:          1          4     3.5877     0.2409       98.25641
INFO:appfl.logger.client_logger_Client12:         1          4     3.5877     0.2409 

cluster ids: [0 0 2 0 0 0 0 3 0 1 1 0]
Update Group model and GG-Correction.
load new group model
load new group model
load new group model
load new group model
tensor([[ 0.2164,  0.2464, -0.0800,  0.3075, -0.0370,  0.0319, -0.1290,  0.1434],
        [ 0.2700, -0.2530,  0.2661,  0.0371,  0.2065,  0.0365,  0.1103, -0.0284]])


appfl: ✅[2026-01-12 05:16:29,510 Client1]:          2          0     0.5877     0.3700           64.0
INFO:appfl.logger.client_logger_Client1:         2          0     0.5877     0.3700           64.0
appfl: ✅[2026-01-12 05:16:30,187 Client1]:          2          1     0.6754     0.2631           91.6
INFO:appfl.logger.client_logger_Client1:         2          1     0.6754     0.2631           91.6
appfl: ✅[2026-01-12 05:16:30,858 Client1]:          2          2     0.6687     0.2415           93.6
INFO:appfl.logger.client_logger_Client1:         2          2     0.6687     0.2415           93.6
appfl: ✅[2026-01-12 05:16:31,519 Client1]:          2          3     0.6575     0.2341           98.4
INFO:appfl.logger.client_logger_Client1:         2          3     0.6575     0.2341           98.4
appfl: ✅[2026-01-12 05:16:32,202 Client1]:          2          4     0.6807     0.2312           95.6
INFO:appfl.logger.client_logger_Client1:         2          4     0.6807     0.2312           

tensor([[ 0.2164,  0.2464, -0.0800,  0.3075, -0.0370,  0.0319, -0.1290,  0.1434],
        [ 0.2700, -0.2530,  0.2661,  0.0371,  0.2065,  0.0365,  0.1103, -0.0284]])


appfl: ✅[2026-01-12 05:16:34,812 Client1]:          2          0     0.6927     0.2415           97.2
INFO:appfl.logger.client_logger_Client1:         2          0     0.6927     0.2415           97.2
appfl: ✅[2026-01-12 05:16:35,486 Client1]:          2          1     0.6720     0.2335           89.6
INFO:appfl.logger.client_logger_Client1:         2          1     0.6720     0.2335           89.6
appfl: ✅[2026-01-12 05:16:36,146 Client1]:          2          2     0.6571     0.2283           98.8
INFO:appfl.logger.client_logger_Client1:         2          2     0.6571     0.2283           98.8
appfl: ✅[2026-01-12 05:16:36,824 Client1]:          2          3     0.6747     0.2269           98.0
INFO:appfl.logger.client_logger_Client1:         2          3     0.6747     0.2269           98.0
appfl: ✅[2026-01-12 05:16:37,481 Client1]:          2          4     0.6545     0.2254           99.2
INFO:appfl.logger.client_logger_Client1:         2          4     0.6545     0.2254           

tensor([[ 0.2164,  0.2464, -0.0800,  0.3075, -0.0370,  0.0319, -0.1290,  0.1434],
        [ 0.2700, -0.2530,  0.2661,  0.0371,  0.2065,  0.0365,  0.1103, -0.0284]])


appfl: ✅[2026-01-12 05:16:39,969 Client2]:          2          0     0.7048     3.9879       94.85715
INFO:appfl.logger.client_logger_Client2:         2          0     0.7048     3.9879       94.85715
appfl: ✅[2026-01-12 05:16:40,671 Client2]:          2          1     0.6997     3.9359      94.571434
INFO:appfl.logger.client_logger_Client2:         2          1     0.6997     3.9359      94.571434
appfl: ✅[2026-01-12 05:16:41,352 Client2]:          2          2     0.6779     3.9282       92.85715
INFO:appfl.logger.client_logger_Client2:         2          2     0.6779     3.9282       92.85715
appfl: ✅[2026-01-12 05:16:42,066 Client2]:          2          3     0.7122     3.9265      89.714294
INFO:appfl.logger.client_logger_Client2:         2          3     0.7122     3.9265      89.714294
appfl: ✅[2026-01-12 05:16:42,758 Client2]:          2          4     0.6891     3.9225       95.14286
INFO:appfl.logger.client_logger_Client2:         2          4     0.6891     3.9225       95.1

tensor([[ 0.2164,  0.2464, -0.0800,  0.3075, -0.0370,  0.0319, -0.1290,  0.1434],
        [ 0.2700, -0.2530,  0.2661,  0.0371,  0.2065,  0.0365,  0.1103, -0.0284]])


appfl: ✅[2026-01-12 05:16:45,203 Client2]:          2          0     0.6941     3.9346           94.0
INFO:appfl.logger.client_logger_Client2:         2          0     0.6941     3.9346           94.0
appfl: ✅[2026-01-12 05:16:45,912 Client2]:          2          1     0.7061     3.9218       93.42857
INFO:appfl.logger.client_logger_Client2:         2          1     0.7061     3.9218       93.42857
appfl: ✅[2026-01-12 05:16:46,543 Client2]:          2          2     0.6280     3.9217       94.00001
INFO:appfl.logger.client_logger_Client2:         2          2     0.6280     3.9217       94.00001
appfl: ✅[2026-01-12 05:16:47,207 Client2]:          2          3     0.6611     3.9161       91.14286
INFO:appfl.logger.client_logger_Client2:         2          3     0.6611     3.9161       91.14286
appfl: ✅[2026-01-12 05:16:47,895 Client2]:          2          4     0.6855     3.9156      94.571434
INFO:appfl.logger.client_logger_Client2:         2          4     0.6855     3.9156      94.57

tensor([[ 0.2828,  0.2874, -0.0906,  0.3201, -0.0681,  0.0813, -0.1667,  0.1847],
        [ 0.3285, -0.2608,  0.3051,  0.0613,  0.2381,  0.0269,  0.1482, -0.0358]])


appfl: ✅[2026-01-12 05:16:50,540 Client3]:          2          0     0.9299 187351130649899264.0000      16.347826
INFO:appfl.logger.client_logger_Client3:         2          0     0.9299 187351130649899264.0000      16.347826
appfl: ✅[2026-01-12 05:16:51,204 Client3]:          2          1     0.6617 44775475229883944.0000      14.695652
INFO:appfl.logger.client_logger_Client3:         2          1     0.6617 44775475229883944.0000      14.695652
appfl: ✅[2026-01-12 05:16:51,962 Client3]:          2          2     0.7543 221837979755754176.0000      17.391304
INFO:appfl.logger.client_logger_Client3:         2          2     0.7543 221837979755754176.0000      17.391304
appfl: ✅[2026-01-12 05:16:52,696 Client3]:          2          3     0.7313 106904539684551824.0000      17.304346
INFO:appfl.logger.client_logger_Client3:         2          3     0.7313 106904539684551824.0000      17.304346
appfl: ✅[2026-01-12 05:16:53,440 Client3]:          2          4     0.7417 18363883041447156.

tensor([[ 0.2828,  0.2874, -0.0906,  0.3201, -0.0681,  0.0813, -0.1667,  0.1847],
        [ 0.3285, -0.2608,  0.3051,  0.0613,  0.2381,  0.0269,  0.1482, -0.0358]])


appfl: ✅[2026-01-12 05:16:55,949 Client3]:          2          0     0.7417 2037116251306521344.0000      15.826088
INFO:appfl.logger.client_logger_Client3:         2          0     0.7417 2037116251306521344.0000      15.826088
appfl: ✅[2026-01-12 05:16:56,705 Client3]:          2          1     0.7529 53780800417620.5078      15.391305
INFO:appfl.logger.client_logger_Client3:         2          1     0.7529 53780800417620.5078      15.391305
appfl: ✅[2026-01-12 05:16:57,450 Client3]:          2          2     0.7430 690681469959356940288.0000      16.782608
INFO:appfl.logger.client_logger_Client3:         2          2     0.7430 690681469959356940288.0000      16.782608
appfl: ✅[2026-01-12 05:16:58,206 Client3]:          2          3     0.7528 959806397195469.5000          100.0
INFO:appfl.logger.client_logger_Client3:         2          3     0.7528 959806397195469.5000          100.0
appfl: ✅[2026-01-12 05:16:58,893 Client3]:          2          4     0.6838    20.0423          10

tensor([[ 0.2164,  0.2464, -0.0800,  0.3075, -0.0370,  0.0319, -0.1290,  0.1434],
        [ 0.2700, -0.2530,  0.2661,  0.0371,  0.2065,  0.0365,  0.1103, -0.0284]])


appfl: ✅[2026-01-12 05:17:01,459 Client4]:          2          0     0.8941    74.2459       99.63637
INFO:appfl.logger.client_logger_Client4:         2          0     0.8941    74.2459       99.63637
appfl: ✅[2026-01-12 05:17:02,151 Client4]:          2          1     0.6890    74.1146      99.696976
INFO:appfl.logger.client_logger_Client4:         2          1     0.6890    74.1146      99.696976
appfl: ✅[2026-01-12 05:17:02,857 Client4]:          2          2     0.7028    74.0488       98.84848
INFO:appfl.logger.client_logger_Client4:         2          2     0.7028    74.0488       98.84848
appfl: ✅[2026-01-12 05:17:03,545 Client4]:          2          3     0.6856    74.0403      99.818184
INFO:appfl.logger.client_logger_Client4:         2          3     0.6856    74.0403      99.818184
appfl: ✅[2026-01-12 05:17:04,236 Client4]:          2          4     0.6895    74.0558       99.39394
INFO:appfl.logger.client_logger_Client4:         2          4     0.6895    74.0558       99.3

tensor([[ 0.2164,  0.2464, -0.0800,  0.3075, -0.0370,  0.0319, -0.1290,  0.1434],
        [ 0.2700, -0.2530,  0.2661,  0.0371,  0.2065,  0.0365,  0.1103, -0.0284]])


appfl: ✅[2026-01-12 05:17:06,649 Client4]:          2          0     0.6776    74.0903          100.0
INFO:appfl.logger.client_logger_Client4:         2          0     0.6776    74.0903          100.0
appfl: ✅[2026-01-12 05:17:07,328 Client4]:          2          1     0.6768    74.0476       99.39394
INFO:appfl.logger.client_logger_Client4:         2          1     0.6768    74.0476       99.39394
appfl: ✅[2026-01-12 05:17:08,013 Client4]:          2          2     0.6819    74.0257       99.93939
INFO:appfl.logger.client_logger_Client4:         2          2     0.6819    74.0257       99.93939
appfl: ✅[2026-01-12 05:17:08,698 Client4]:          2          3     0.6828    74.0164      99.272736
INFO:appfl.logger.client_logger_Client4:         2          3     0.6828    74.0164      99.272736
appfl: ✅[2026-01-12 05:17:09,385 Client4]:          2          4     0.6847    74.0153       99.39394
INFO:appfl.logger.client_logger_Client4:         2          4     0.6847    74.0153       99.3

tensor([[ 0.2164,  0.2464, -0.0800,  0.3075, -0.0370,  0.0319, -0.1290,  0.1434],
        [ 0.2700, -0.2530,  0.2661,  0.0371,  0.2065,  0.0365,  0.1103, -0.0284]])


appfl: ✅[2026-01-12 05:17:11,800 Client5]:          2          0     0.7254    12.1410       83.33334
INFO:appfl.logger.client_logger_Client5:         2          0     0.7254    12.1410       83.33334
appfl: ✅[2026-01-12 05:17:12,503 Client5]:          2          1     0.7007    10.8220           82.0
INFO:appfl.logger.client_logger_Client5:         2          1     0.7007    10.8220           82.0
appfl: ✅[2026-01-12 05:17:13,228 Client5]:          2          2     0.7219    10.5534       91.50001
INFO:appfl.logger.client_logger_Client5:         2          2     0.7219    10.5534       91.50001
appfl: ✅[2026-01-12 05:17:13,914 Client5]:          2          3     0.6830    10.4602       90.00001
INFO:appfl.logger.client_logger_Client5:         2          3     0.6830    10.4602       90.00001
appfl: ✅[2026-01-12 05:17:14,633 Client5]:          2          4     0.7170    10.7971       91.33333
INFO:appfl.logger.client_logger_Client5:         2          4     0.7170    10.7971       91.3

tensor([[ 0.2164,  0.2464, -0.0800,  0.3075, -0.0370,  0.0319, -0.1290,  0.1434],
        [ 0.2700, -0.2530,  0.2661,  0.0371,  0.2065,  0.0365,  0.1103, -0.0284]])


appfl: ✅[2026-01-12 05:17:16,997 Client5]:          2          0     0.6990    11.9311       84.50001
INFO:appfl.logger.client_logger_Client5:         2          0     0.6990    11.9311       84.50001
appfl: ✅[2026-01-12 05:17:17,704 Client5]:          2          1     0.7053    10.7790       91.66668
INFO:appfl.logger.client_logger_Client5:         2          1     0.7053    10.7790       91.66668
appfl: ✅[2026-01-12 05:17:18,402 Client5]:          2          2     0.6943    10.3927       89.33334
INFO:appfl.logger.client_logger_Client5:         2          2     0.6943    10.3927       89.33334
appfl: ✅[2026-01-12 05:17:19,122 Client5]:          2          3     0.7172    10.4177       90.33334
INFO:appfl.logger.client_logger_Client5:         2          3     0.7172    10.4177       90.33334
appfl: ✅[2026-01-12 05:17:19,835 Client5]:          2          4     0.7104    10.4786       87.66668
INFO:appfl.logger.client_logger_Client5:         2          4     0.7104    10.4786       87.6

tensor([[ 0.2164,  0.2464, -0.0800,  0.3075, -0.0370,  0.0319, -0.1290,  0.1434],
        [ 0.2700, -0.2530,  0.2661,  0.0371,  0.2065,  0.0365,  0.1103, -0.0284]])


appfl: ✅[2026-01-12 05:17:22,273 Client6]:          2          0     0.7214    10.7942      96.740746
INFO:appfl.logger.client_logger_Client6:         2          0     0.7214    10.7942      96.740746
appfl: ✅[2026-01-12 05:17:22,968 Client6]:          2          1     0.6925     9.9040      99.296295
INFO:appfl.logger.client_logger_Client6:         2          1     0.6925     9.9040      99.296295
appfl: ✅[2026-01-12 05:17:23,668 Client6]:          2          2     0.6983     9.8515      97.814804
INFO:appfl.logger.client_logger_Client6:         2          2     0.6983     9.8515      97.814804
appfl: ✅[2026-01-12 05:17:24,365 Client6]:          2          3     0.6944     9.8483       97.03703
INFO:appfl.logger.client_logger_Client6:         2          3     0.6944     9.8483       97.03703
appfl: ✅[2026-01-12 05:17:25,066 Client6]:          2          4     0.6978     9.8464      97.259254
INFO:appfl.logger.client_logger_Client6:         2          4     0.6978     9.8464      97.25

tensor([[ 0.2164,  0.2464, -0.0800,  0.3075, -0.0370,  0.0319, -0.1290,  0.1434],
        [ 0.2700, -0.2530,  0.2661,  0.0371,  0.2065,  0.0365,  0.1103, -0.0284]])


appfl: ✅[2026-01-12 05:17:27,550 Client6]:          2          0     0.7212    10.0692       96.70371
INFO:appfl.logger.client_logger_Client6:         2          0     0.7212    10.0692       96.70371
appfl: ✅[2026-01-12 05:17:28,237 Client6]:          2          1     0.6843     9.8526        98.4074
INFO:appfl.logger.client_logger_Client6:         2          1     0.6843     9.8526        98.4074
appfl: ✅[2026-01-12 05:17:28,908 Client6]:          2          2     0.6684     9.8258       99.33333
INFO:appfl.logger.client_logger_Client6:         2          2     0.6684     9.8258       99.33333
appfl: ✅[2026-01-12 05:17:29,543 Client6]:          2          3     0.6321     9.8195       99.62963
INFO:appfl.logger.client_logger_Client6:         2          3     0.6321     9.8195       99.62963
appfl: ✅[2026-01-12 05:17:30,242 Client6]:          2          4     0.6963     9.8127       99.33333
INFO:appfl.logger.client_logger_Client6:         2          4     0.6963     9.8127       99.3

tensor([[ 0.2164,  0.2464, -0.0800,  0.3075, -0.0370,  0.0319, -0.1290,  0.1434],
        [ 0.2700, -0.2530,  0.2661,  0.0371,  0.2065,  0.0365,  0.1103, -0.0284]])


appfl: ✅[2026-01-12 05:17:33,062 Client7]:          2          0     1.0620    14.3063       99.16667
INFO:appfl.logger.client_logger_Client7:         2          0     1.0620    14.3063       99.16667
appfl: ✅[2026-01-12 05:17:33,958 Client7]:          2          1     0.8942    12.4667       97.83333
INFO:appfl.logger.client_logger_Client7:         2          1     0.8942    12.4667       97.83333
appfl: ✅[2026-01-12 05:17:34,831 Client7]:          2          2     0.8716    11.9142       99.33334
INFO:appfl.logger.client_logger_Client7:         2          2     0.8716    11.9142       99.33334
appfl: ✅[2026-01-12 05:17:35,721 Client7]:          2          3     0.8872    12.2281       99.66667
INFO:appfl.logger.client_logger_Client7:         2          3     0.8872    12.2281       99.66667
appfl: ✅[2026-01-12 05:17:36,611 Client7]:          2          4     0.8881    11.9760       98.83334
INFO:appfl.logger.client_logger_Client7:         2          4     0.8881    11.9760       98.8

tensor([[ 0.2164,  0.2464, -0.0800,  0.3075, -0.0370,  0.0319, -0.1290,  0.1434],
        [ 0.2700, -0.2530,  0.2661,  0.0371,  0.2065,  0.0365,  0.1103, -0.0284]])


appfl: ✅[2026-01-12 05:17:39,205 Client7]:          2          0     0.8621    12.0098       99.83333
INFO:appfl.logger.client_logger_Client7:         2          0     0.8621    12.0098       99.83333
appfl: ✅[2026-01-12 05:17:40,103 Client7]:          2          1     0.8949    11.8475       97.66667
INFO:appfl.logger.client_logger_Client7:         2          1     0.8949    11.8475       97.66667
appfl: ✅[2026-01-12 05:17:40,969 Client7]:          2          2     0.8643    11.9231       99.83334
INFO:appfl.logger.client_logger_Client7:         2          2     0.8643    11.9231       99.83334
appfl: ✅[2026-01-12 05:17:41,837 Client7]:          2          3     0.8652    11.8567           99.0
INFO:appfl.logger.client_logger_Client7:         2          3     0.8652    11.8567           99.0
appfl: ✅[2026-01-12 05:17:42,757 Client7]:          2          4     0.9184    11.7712       99.33334
INFO:appfl.logger.client_logger_Client7:         2          4     0.9184    11.7712       99.3

tensor([[ 0.2663,  0.2865, -0.1012,  0.3212, -0.0436,  0.0879, -0.1364,  0.1743],
        [ 0.3229, -0.2493,  0.3143,  0.0599,  0.2677,  0.0584,  0.1491, -0.0660]])


appfl: ✅[2026-01-12 05:17:45,432 Client8]:          2          0     0.8434     0.1875          100.0
INFO:appfl.logger.client_logger_Client8:         2          0     0.8434     0.1875          100.0
appfl: ✅[2026-01-12 05:17:46,156 Client8]:          2          1     0.7210     0.0938       99.88571
INFO:appfl.logger.client_logger_Client8:         2          1     0.7210     0.0938       99.88571
appfl: ✅[2026-01-12 05:17:46,943 Client8]:          2          2     0.7848     0.1468      99.828575
INFO:appfl.logger.client_logger_Client8:         2          2     0.7848     0.1468      99.828575
appfl: ✅[2026-01-12 05:17:47,744 Client8]:          2          3     0.7997     0.1117          100.0
INFO:appfl.logger.client_logger_Client8:         2          3     0.7997     0.1117          100.0
appfl: ✅[2026-01-12 05:17:48,509 Client8]:          2          4     0.7626     0.1023          100.0
INFO:appfl.logger.client_logger_Client8:         2          4     0.7626     0.1023          1

tensor([[ 0.2663,  0.2865, -0.1012,  0.3212, -0.0436,  0.0879, -0.1364,  0.1743],
        [ 0.3229, -0.2493,  0.3143,  0.0599,  0.2677,  0.0584,  0.1491, -0.0660]])


appfl: ✅[2026-01-12 05:17:51,039 Client8]:          2          0     0.7828     0.2957       99.54286
INFO:appfl.logger.client_logger_Client8:         2          0     0.7828     0.2957       99.54286
appfl: ✅[2026-01-12 05:17:51,804 Client8]:          2          1     0.7635     0.0545          100.0
INFO:appfl.logger.client_logger_Client8:         2          1     0.7635     0.0545          100.0
appfl: ✅[2026-01-12 05:17:52,593 Client8]:          2          2     0.7863     0.1322          100.0
INFO:appfl.logger.client_logger_Client8:         2          2     0.7863     0.1322          100.0
appfl: ✅[2026-01-12 05:17:53,360 Client8]:          2          3     0.7661     0.1084          100.0
INFO:appfl.logger.client_logger_Client8:         2          3     0.7661     0.1084          100.0
appfl: ✅[2026-01-12 05:17:54,143 Client8]:          2          4     0.7802     0.0415      98.628586
INFO:appfl.logger.client_logger_Client8:         2          4     0.7802     0.0415      98.62

tensor([[ 0.2164,  0.2464, -0.0800,  0.3075, -0.0370,  0.0319, -0.1290,  0.1434],
        [ 0.2700, -0.2530,  0.2661,  0.0371,  0.2065,  0.0365,  0.1103, -0.0284]])


appfl: ✅[2026-01-12 05:17:57,207 Client9]:          2          0     1.0616     1.8101          100.0
INFO:appfl.logger.client_logger_Client9:         2          0     1.0616     1.8101          100.0
appfl: ✅[2026-01-12 05:17:58,072 Client9]:          2          1     0.8634     0.1447          100.0
INFO:appfl.logger.client_logger_Client9:         2          1     0.8634     0.1447          100.0
appfl: ✅[2026-01-12 05:17:58,886 Client9]:          2          2     0.8116     0.1344          100.0
INFO:appfl.logger.client_logger_Client9:         2          2     0.8116     0.1344          100.0
appfl: ✅[2026-01-12 05:17:59,683 Client9]:          2          3     0.7943     0.1302          100.0
INFO:appfl.logger.client_logger_Client9:         2          3     0.7943     0.1302          100.0
appfl: ✅[2026-01-12 05:18:00,519 Client9]:          2          4     0.8343     0.1284          100.0
INFO:appfl.logger.client_logger_Client9:         2          4     0.8343     0.1284          1

tensor([[ 0.2164,  0.2464, -0.0800,  0.3075, -0.0370,  0.0319, -0.1290,  0.1434],
        [ 0.2700, -0.2530,  0.2661,  0.0371,  0.2065,  0.0365,  0.1103, -0.0284]])


appfl: ✅[2026-01-12 05:18:03,321 Client9]:          2          0     0.8799     0.1285          100.0
INFO:appfl.logger.client_logger_Client9:         2          0     0.8799     0.1285          100.0
appfl: ✅[2026-01-12 05:18:04,117 Client9]:          2          1     0.7931     0.1249          100.0
INFO:appfl.logger.client_logger_Client9:         2          1     0.7931     0.1249          100.0
appfl: ✅[2026-01-12 05:18:04,967 Client9]:          2          2     0.8478     0.1225          100.0
INFO:appfl.logger.client_logger_Client9:         2          2     0.8478     0.1225          100.0
appfl: ✅[2026-01-12 05:18:05,801 Client9]:          2          3     0.8323     0.1214          100.0
INFO:appfl.logger.client_logger_Client9:         2          3     0.8323     0.1214          100.0
appfl: ✅[2026-01-12 05:18:06,636 Client9]:          2          4     0.8334     0.1213          100.0
INFO:appfl.logger.client_logger_Client9:         2          4     0.8334     0.1213          1

tensor([[ 0.2654,  0.2878, -0.0877,  0.3147, -0.0718,  0.0756, -0.1464,  0.1970],
        [ 0.3158, -0.2521,  0.3006,  0.0621,  0.2562,  0.0430,  0.1440, -0.0430]])


appfl: ✅[2026-01-12 05:18:10,170 Client10]:          2          0     1.6529    43.6268       94.51685
INFO:appfl.logger.client_logger_Client10:         2          0     1.6529    43.6268       94.51685
appfl: ✅[2026-01-12 05:18:11,574 Client10]:          2          1     1.4030    35.2383       95.88765
INFO:appfl.logger.client_logger_Client10:         2          1     1.4030    35.2383       95.88765
appfl: ✅[2026-01-12 05:18:12,940 Client10]:          2          2     1.3648    31.9139        96.1573
INFO:appfl.logger.client_logger_Client10:         2          2     1.3648    31.9139        96.1573
appfl: ✅[2026-01-12 05:18:14,299 Client10]:          2          3     1.3576    31.8051       95.41574
INFO:appfl.logger.client_logger_Client10:         2          3     1.3576    31.8051       95.41574
appfl: ✅[2026-01-12 05:18:15,677 Client10]:          2          4     1.3766    31.3694       97.34832
INFO:appfl.logger.client_logger_Client10:         2          4     1.3766    31.3694 

tensor([[ 0.2654,  0.2878, -0.0877,  0.3147, -0.0718,  0.0756, -0.1464,  0.1970],
        [ 0.3158, -0.2521,  0.3006,  0.0621,  0.2562,  0.0430,  0.1440, -0.0430]])


appfl: ✅[2026-01-12 05:18:21,456 Client11]:          2          0     3.8332   201.3453       85.07693
INFO:appfl.logger.client_logger_Client11:         2          0     3.8332   201.3453       85.07693
appfl: ✅[2026-01-12 05:18:24,340 Client11]:          2          1     2.8826   153.3899      87.446144
INFO:appfl.logger.client_logger_Client11:         2          1     2.8826   153.3899      87.446144
appfl: ✅[2026-01-12 05:18:27,294 Client11]:          2          2     2.9525   146.9007       91.43076
INFO:appfl.logger.client_logger_Client11:         2          2     2.9525   146.9007       91.43076
appfl: ✅[2026-01-12 05:18:30,265 Client11]:          2          3     2.9685   145.8831       87.08461
INFO:appfl.logger.client_logger_Client11:         2          3     2.9685   145.8831       87.08461
appfl: ✅[2026-01-12 05:18:33,051 Client11]:          2          4     2.7841   145.3546       89.96923
INFO:appfl.logger.client_logger_Client11:         2          4     2.7841   145.3546 

tensor([[ 0.2164,  0.2464, -0.0800,  0.3075, -0.0370,  0.0319, -0.1290,  0.1434],
        [ 0.2700, -0.2530,  0.2661,  0.0371,  0.2065,  0.0365,  0.1103, -0.0284]])


cuDSSError: ALLOC_FAILED (2)

In [ ]:
estimated_cluster_ids

array([2, 3, 0, 2, 2, 3, 0, 2, 3, 1, 1, 3])

## Evaluate model on "test dataset" for each client

In [11]:
# Modifies stats in place
def dict_agg(stats, key, value, op='concat'):
    if key in stats.keys():
        if op == 'sum':
            stats[key] += value
        elif op == 'concat':
            stats[key] = np.concatenate((stats[key], value), axis=0)
        else:
            raise NotImplementedError
    else:
        stats[key] = value

In [12]:
from torch_geometric.loader import DataLoader
from pypower.api import makeYbus
import torch
import numpy as np
import time

for client_agent in client_agents:
    print(client_agent.get_id())
    test_dataloader = DataLoader(
            client_agent.test_dataset,
            batch_size=1,
            shuffle=False,
            drop_last=True
        )

    Ybus, Yf, Yt = makeYbus(client_agent.dataset.baseMVA, client_agent.dataset.ppc['bus'], client_agent.dataset.ppc['branch'])
    # branch thermal limit information
    flow_max = (client_agent.dataset.ppc['branch'][:, 5] / client_agent.dataset.baseMVA)**2
    flow_max[flow_max == 0] = np.inf # np.Inf
    flow_max = torch.tensor(flow_max, dtype=torch.float32).to(client_agent.dataset.device)

    test_len = 200
    node_means, node_stds, edge_means, edge_stds = client_agent.dataset.input_standardization(test_len, train=False) # (1, 2*nbus) <= for data normalization
    n_means = node_means.to(client_agent.dataset.device)
    n_stds = node_stds.to(client_agent.dataset.device)
    e_means = edge_means.to(client_agent.dataset.device)
    e_stds = edge_stds.to(client_agent.dataset.device)

    client_agent.model.eval()
    test_stats = {}
    test_eps_converge = 1e-4

    # LagM = torch.ones(1, 2*ng + 2*nbus + 2*nl).to(DEVICE) # shape: (1, num_inequalities)
    LagM_sp_g = torch.ones(1, 2).to(client_agent.dataset.device) # shape: (1, num_inequalities)
    LagM_q_g = torch.ones(1, 2*client_agent.dataset.ng).to(client_agent.dataset.device) # shape: (1, num_inequalities)
    LagM_v_m = torch.ones(1, 2*client_agent.dataset.nbus).to(client_agent.dataset.device) # shape: (1, num_inequalities)
    LagM_line_l = torch.ones(1, 2*client_agent.dataset.nl).to(client_agent.dataset.device) # shape: (1, num_inequalities)

    solve_time = []
    with torch.no_grad():
        for (i, Xtest) in enumerate(test_dataloader):
            Xtest = Xtest.to(client_agent.dataset.device)

            start_time = time.time()
            Y = client_agent.model(Xtest, n_means, n_stds, e_means, e_stds)
            end_time = time.time()

            solve_time += [end_time - start_time]

            ## line thermal limit
            pg, qg, vm, va = client_agent.dataset.get_yvars(Y)
            vr = vm*torch.cos(va)
            vi = vm*torch.sin(va)
            vz = torch.complex(vr, vi) # complex voltage

            # calculate the branch current of from bus and to bus based on the Yf*V and Yt*V
            If = torch.tensor(Yf.todense(), dtype=torch.complex64).to(client_agent.dataset.device) @ vz.T
            It = torch.tensor(Yt.todense(), dtype=torch.complex64).to(client_agent.dataset.device) @ vz.T

            # Calculate the apparent power S
            Sf = vz[:,client_agent.dataset.ppc['branch'][:,0].astype(int)] * torch.conj(If.T)
            St = vz[:,client_agent.dataset.ppc['branch'][:,1].astype(int)] * torch.conj(It.T)
            Sff = Sf * torch.conj(Sf)
            Stt = St * torch.conj(St)

            # calculate the line thermal limit constraints violation
            diff_Sf = Sff.real - flow_max
            diff_St = Stt.real - flow_max
            # diff_Sf[torch.clamp(diff_Sf, 0) != 0]

            line_limit_vio_Sf = torch.clamp(diff_Sf, 0)
            line_limit_vio_St = torch.clamp(diff_St, 0)
            ###########################################

            # test_loss, test_obj_cost, test_ineq_dist, test_eq_resid = total_loss(data, Xtest.x, Y, LagM)
            test_loss, test_obj_cost, test_ineq_dist, test_eq_resid = client_agent.loss_fn.forward(client_agent.dataset, Xtest.x, Y, LagM_sp_g, LagM_q_g, LagM_v_m, LagM_line_l) # LagM is lagrangian multiplier, and the shape is (1, num_inequalities)

            dict_agg(test_stats, 'time', np.array(end_time - start_time).reshape(1,-1))

            # test_ineq_p_g = torch.cat([pg - client_agent.dataset.pmax.to(client_agent.dataset.device), client_agent.dataset.pmin.to(client_agent.dataset.device) - pg], dim=1)
            # test_ineq_p_g = torch.clamp(test_ineq_p_g, 0).to(client_agent.dataset.device)
            test_ineq_p_g = test_ineq_dist[:,:2]
            test_ineq_q_g = test_ineq_dist[:,2:2+2*client_agent.dataset.ng]
            test_ineq_v_m = test_ineq_dist[:,2+2*client_agent.dataset.ng:2+2*client_agent.dataset.ng+2*client_agent.dataset.nbus]
            test_ineq_line_l = test_ineq_dist[:,2+2*client_agent.dataset.ng+2*client_agent.dataset.nbus:]

            dict_agg(test_stats, 'test_loss', test_loss.detach().cpu().numpy())
            # dict_agg(test_stats, 'test_loss', (test_loss[0]+test_loss[1]+test_loss[2]+test_loss[3]).detach().cpu().numpy())

            dict_agg(test_stats, 'test_obj_cost', test_obj_cost.detach().cpu().numpy())

            dict_agg(test_stats, 'test_ineq_max', torch.max(test_ineq_dist, dim=1)[0].detach().cpu().numpy())
            dict_agg(test_stats, 'test_ineq_mean', torch.mean(test_ineq_dist, dim=1).detach().cpu().numpy())
            dict_agg(test_stats, 'test_ineq_p_g_max', torch.max(test_ineq_p_g, dim=1)[0].detach().cpu().numpy())
            dict_agg(test_stats, 'test_ineq_p_g_mean', torch.mean(test_ineq_p_g, dim=1).detach().cpu().numpy())
            dict_agg(test_stats, 'test_ineq_q_g_max', torch.max(test_ineq_q_g, dim=1)[0].detach().cpu().numpy())
            dict_agg(test_stats, 'test_ineq_q_g_mean', torch.mean(test_ineq_q_g, dim=1).detach().cpu().numpy())
            dict_agg(test_stats, 'test_ineq_v_m_max', torch.max(test_ineq_v_m, dim=1)[0].detach().cpu().numpy())
            dict_agg(test_stats, 'test_ineq_v_m_mean', torch.mean(test_ineq_v_m, dim=1).detach().cpu().numpy())
            dict_agg(test_stats, 'test_ineq_line_l_max', torch.max(test_ineq_line_l, dim=1)[0].detach().cpu().numpy())
            dict_agg(test_stats, 'test_ineq_line_l_mean', torch.mean(test_ineq_line_l, dim=1).detach().cpu().numpy())

            pg_rate_torch = (((pg <= client_agent.dataset.pmax.to(client_agent.dataset.device)) & (pg >= client_agent.dataset.pmin.to(client_agent.dataset.device))).sum()/client_agent.dataset.ng)*100
            qg_rate_torch = (((qg <= client_agent.dataset.qmax.to(client_agent.dataset.device)) & (qg >= client_agent.dataset.qmin.to(client_agent.dataset.device))).sum()/client_agent.dataset.ng)*100
            dict_agg(test_stats, 'test_p_g_satisfication rate (%)', pg_rate_torch.detach().cpu().numpy().reshape(-1,1))
            dict_agg(test_stats, 'test_q_g_satisfication rate (%)', qg_rate_torch.detach().cpu().numpy().reshape(-1,1))
            # dict_agg(test_stats, 'test_p_g_satisfication rate (%)', ((torch.sum(test_ineq_p_g == 0, dim=1)/test_ineq_p_g.shape[1])*100).detach().cpu().numpy())
            # dict_agg(test_stats, 'test_q_g_satisfication rate (%)', ((torch.sum(test_ineq_q_g == 0, dim=1)/test_ineq_q_g.shape[1])*100).detach().cpu().numpy())

            v_rate_torch = (((vm <= client_agent.dataset.vmax.to(client_agent.dataset.device)) & (vm >= client_agent.dataset.vmin.to(client_agent.dataset.device))).sum()/client_agent.dataset.nbus)*100
            dict_agg(test_stats, 'test_v_m_satisfication rate (%)', v_rate_torch.detach().cpu().numpy().reshape(-1,1))
            # dict_agg(test_stats, 'test_v_m_satisfication rate (%)', ((torch.sum(test_ineq_v_m == 0, dim=1)/test_ineq_v_m.shape[1])*100).detach().cpu().numpy())

            sff_rate_torch = ((Sff.real <= flow_max).sum()/client_agent.dataset.nl)*100        
            stt_rate_torch = ((Stt.real <= flow_max).sum()/client_agent.dataset.nl)*100        
            dict_agg(test_stats, 'test_line_limit_satisfication_rate_Sf(%)', sff_rate_torch.detach().cpu().numpy().reshape(-1,1))
            dict_agg(test_stats, 'test_line_limit_satisfication_rate_St(%)', stt_rate_torch.detach().cpu().numpy().reshape(-1,1))
            dict_agg(test_stats, 'test_line_limit_satisfication_rate (%)', ((torch.sum(test_ineq_line_l == 0, dim=1)/test_ineq_line_l.shape[1])*100).detach().cpu().numpy())
            # dict_agg(test_stats, 'test_line_limit_satisfication_rate_Sf(%)', ((torch.sum(line_limit_vio_Sf == 0, dim=1)/line_limit_vio_Sf.shape[1])*100).detach().cpu().numpy())
            # dict_agg(test_stats, 'test_line_limit_satisfication_rate_St(%)', ((torch.sum(line_limit_vio_St == 0, dim=1)/line_limit_vio_St.shape[1])*100).detach().cpu().numpy())

            dict_agg(test_stats, 'test_ineq_q_g_num_viol_0', torch.sum(test_ineq_q_g > test_eps_converge, dim=1).detach().cpu().numpy())
            dict_agg(test_stats, 'test_ineq_v_m_num_viol_0', torch.sum(test_ineq_v_m > test_eps_converge, dim=1).detach().cpu().numpy())

            test_eq_real = test_eq_resid[:,:client_agent.dataset.nbus]
            test_eq_react = test_eq_resid[:,client_agent.dataset.nbus:]
            dict_agg(test_stats, 'test_eq_max', torch.max(torch.abs(test_eq_resid), dim=1)[0].detach().cpu().numpy())
            dict_agg(test_stats, 'test_eq_mean', torch.mean(torch.abs(test_eq_resid), dim=1).detach().cpu().numpy())
            dict_agg(test_stats, 'test_eq_real_max', torch.max(torch.abs(test_eq_real), dim=1)[0].detach().cpu().numpy())
            dict_agg(test_stats, 'test_eq_real_mean', torch.mean(torch.abs(test_eq_real), dim=1).detach().cpu().numpy())
            dict_agg(test_stats, 'test_eq_react_max', torch.max(torch.abs(test_eq_react), dim=1)[0].detach().cpu().numpy())
            dict_agg(test_stats, 'test_eq_react_mean', torch.mean(torch.abs(test_eq_react), dim=1).detach().cpu().numpy())
            dict_agg(test_stats, 'test_active_eq_satisfication rate (%)', (torch.sum((test_eq_resid[:,:client_agent.dataset.nbus] <= 1e-2) & (test_eq_resid[:,:client_agent.dataset.nbus] >= -1e-2)  , dim=1)/test_eq_resid[:,:client_agent.dataset.nbus].shape[1]*100).detach().cpu().numpy())
            dict_agg(test_stats, 'test_reactive_eq_satisfication rate (%)', (torch.sum((test_eq_resid[:,client_agent.dataset.nbus:] <= 1e-2) & (test_eq_resid[:,client_agent.dataset.nbus:] >= -1e-2)  , dim=1)/test_eq_resid[:,client_agent.dataset.nbus:].shape[1]*100).detach().cpu().numpy())

    print("GraphLDE obj. value for test samples: ", np.round(np.mean(test_stats['test_obj_cost'])*10000, 4))
    print("GraphLDE eq. mean for test samples: ", np.mean(test_stats['test_eq_mean']))
    print("GraphLDE eq. max for test samples: ", np.mean(test_stats['test_eq_max']))
    print("GraphLDE eq. active mean for test samples: ", np.mean(test_stats['test_eq_real_mean']))
    print("GraphLDE eq. active max for test samples: ", np.mean(test_stats['test_eq_real_max']))
    print("GraphLDE eq. reactive mean for test samples: ", np.mean(test_stats['test_eq_react_mean']))
    print("GraphLDE eq. reactive max for test samples: ", np.mean(test_stats['test_eq_react_max']))

    print("\n")
    print("GraphLDE ineq. mean for test samples: ", np.mean(test_stats['test_ineq_mean']))
    print("GraphLDE ineq. max for test samples: ", np.mean(test_stats['test_ineq_max']))
    print("GraphLDE ineq. p_g mean for test samples: ", np.mean(test_stats['test_ineq_p_g_mean']))
    print("GraphLDE ineq. p_g max for test samples: ", np.mean(test_stats['test_ineq_p_g_max']))
    print("GraphLDE ineq. q_g mean for test samples: ", np.mean(test_stats['test_ineq_q_g_mean']))
    print("GraphLDE ineq. q_g max for test samples: ", np.mean(test_stats['test_ineq_q_g_max']))
    print("GraphLDE ineq. v_m mean for test samples: ", np.mean(test_stats['test_ineq_v_m_mean']))
    print("GraphLDE ineq. v_m max for test samples: ", np.mean(test_stats['test_ineq_v_m_max']))
    print("GraphLDE ineq. line_l mean for test samples: ", np.mean(test_stats['test_ineq_line_l_mean']))
    print("GraphLDE ineq. line_l max for test samples: ", np.mean(test_stats['test_ineq_line_l_max']))

    print("\n")
    print("GraphLDE p_g satisfication rate for test samples: ", np.mean(test_stats['test_p_g_satisfication rate (%)']))
    print("GraphLDE q_g satisfication rate for test samples: ", np.mean(test_stats['test_q_g_satisfication rate (%)']))
    print("GraphLDE v_m satisfication rate for test samples: ", np.mean(test_stats['test_v_m_satisfication rate (%)']))
    print("GraphLDE test_line_limit_satisfication_rate_Sf for test samples: ", np.mean(test_stats['test_line_limit_satisfication_rate_Sf(%)']))
    print("GraphLDE test_line_limit_satisfication_rate_St for test samples: ", np.mean(test_stats['test_line_limit_satisfication_rate_St(%)']))
    print("GraphLDE active eq satisfication rate for test samples: ", np.mean(test_stats['test_active_eq_satisfication rate (%)']))
    print("GraphLDE reactive eq satisfication rate for test samples: ", np.mean(test_stats['test_reactive_eq_satisfication rate (%)']))

    print("\n")
    print("GraphLDE time (ms) <== average value for test dataset:", (np.mean(test_stats['time']*1e3)))
    print('\n')

# [14, 57, 60, 73, 89, 118, 162, 197, 250, 793, 1354, 1664]

Client1
GraphLDE obj. value for test samples:  2179.1168
GraphLDE eq. mean for test samples:  4.5920024e-05
GraphLDE eq. max for test samples:  0.00040408384
GraphLDE eq. active mean for test samples:  4.0165687e-05
GraphLDE eq. active max for test samples:  0.00018686285
GraphLDE eq. reactive mean for test samples:  5.167436e-05
GraphLDE eq. reactive max for test samples:  0.000404082


GraphLDE ineq. mean for test samples:  1.755544e-05
GraphLDE ineq. max for test samples:  0.0012682964
GraphLDE ineq. p_g mean for test samples:  0.0
GraphLDE ineq. p_g max for test samples:  0.0
GraphLDE ineq. q_g mean for test samples:  0.00014044352
GraphLDE ineq. q_g max for test samples:  0.0012682964
GraphLDE ineq. v_m mean for test samples:  0.0
GraphLDE ineq. v_m max for test samples:  0.0
GraphLDE ineq. line_l mean for test samples:  0.0
GraphLDE ineq. line_l max for test samples:  0.0


GraphLDE p_g satisfication rate for test samples:  100.0
GraphLDE q_g satisfication rate for test samples: 